# Generated by Django 3.2.23 on 2023-12-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='')),
                ('DOB', models.DateField()),
                ('Phone', models.BigIntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=90)),
                ('Email', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='patient_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=80)),
                ('Last_name', models.CharField(max_length=80)),
                ('Gender', models.CharField(max_length=80)),
                ('DOB', models.DateField()),
                ('Place', models.CharField(max_length=70)),
                ('Post', models.CharField(max_length=80)),
                ('Pin', models.BigIntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=70)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField()),
                ('Date', models.DateField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.doctor_table')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.patient_table')),
            ],
        ),
        migrations.CreateModel(
            name='emergencyrequest_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Lattitude', models.FloatField()),
                ('Lougitude', models.FloatField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.patient_table')),
            ],
        ),
        migrations.AddField(
            model_name='doctor_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.login_table'),
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complints', models.TextField()),
                ('Date', models.DateField()),
                ('Replay', models.CharField(max_length=100)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.doctor_table')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.patient_table')),
            ],
        ),
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('Date', models.DateField()),
                ('Fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fromid', to='MEDICARE.login_table')),
                ('Toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Toid', to='MEDICARE.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='appoiment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.patient_table')),
            ],
        ),
    ]
