# Generated by Django 3.2.23 on 2023-12-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MEDICARE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=90)),
                ('Riview', models.CharField(max_length=90)),
                ('Date', models.CharField(max_length=90)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.doctor_table')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.patient_table')),
            ],
        ),
    ]
