# Generated by Django 3.2.23 on 2023-12-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MEDICARE', '0002_rating_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeshedule_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_time', models.TimeField()),
                ('To_time', models.TimeField()),
                ('Day', models.CharField(max_length=90)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.doctor_table')),
            ],
        ),
    ]
