# Generated by Django 3.2.23 on 2023-12-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MEDICARE', '0003_timeshedule_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewprescription_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=90)),
                ('date', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.doctor_table')),
            ],
        ),
    ]
