# Generated by Django 3.2.23 on 2023-12-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MEDICARE', '0004_viewprescription_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoiment_table',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.doctor_table'),
            preserve_default=False,
        ),
    ]
