# Generated by Django 3.2.23 on 2023-12-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MEDICARE', '0005_appoiment_table_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyrequest_table',
            old_name='Lougitude',
            new_name='lougitude',
        ),
        migrations.RemoveField(
            model_name='appoiment_table',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appoiment_table',
            name='Timeshedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.timeshedule_table'),
            preserve_default=False,
        ),
    ]
