# Generated by Django 3.2.23 on 2023-12-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MEDICARE', '0007_auto_20231215_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewprescription_table',
            name='Patientid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.login_table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewprescription_table',
            name='prescription',
            field=models.TextField(),
        ),
    ]
