# Generated by Django 3.2.23 on 2023-12-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MEDICARE', '0008_auto_20231215_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewprescription_table',
            name='Patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEDICARE.patient_table'),
        ),
    ]
