# Generated by Django 3.2.23 on 2023-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDICARE', '0009_alter_viewprescription_table_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_table',
            name='image',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
