# Generated by Django 3.2.23 on 2024-02-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MEDICARE', '0010_patient_table_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emergencyrequest_table',
        ),
    ]
